export const ERR = {
  VALIDATION: ['VALIDATION_ERROR', 422], UNAUTHORIZED: ['AUTH_UNAUTHORIZED', 401],
  FORBIDDEN: ['AUTH_FORBIDDEN', 403], NOT_FOUND: ['RESOURCE_NOT_FOUND', 404],
  EMAIL_TAKEN: ['EMAIL_TAKEN', 409], AUTH_INVALID_CRED: ['AUTH_INVALID_CREDENTIALS', 401],
  ACCOUNT_LOCKED: ['ACCOUNT_LOCKED', 403], ACCOUNT_PENDING: ['ACCOUNT_PENDING', 403],
  OTP_INVALID: ['OTP_INVALID', 400], OTP_EXPIRED: ['OTP_EXPIRED', 400],
  OTP_RESEND_COOLDOWN: ['OTP_RESEND_COOLDOWN', 429], OTP_TOO_MANY_ATTEMPTS: ['OTP_TOO_MANY_ATTEMPTS', 429],
  REFRESH_REUSED: ['REFRESH_REUSED', 401], RESET_TOKEN_INVALID: ['RESET_TOKEN_INVALID', 400],
  PASSWORD_MISMATCH: ['PASSWORD_MISMATCH', 400], INTERNAL: ['INTERNAL_ERROR', 500],
  RATE_LIMITED: ['RATE_LIMITED', 429],
  BOOK_NOT_FOUND: ['BOOK_NOT_FOUND', 404],
  CATEGORY_NOT_FOUND: ['CATEGORY_NOT_FOUND', 404],
} as const;
export type ErrKey = keyof typeof ERR;
